karmaradio/karma

config/test.exs
test/controllers/auth_test.exs
test/controllers/page_controller_test.exs
test/controllers/session_controller_test.exs
test/controllers/user_controller_test.exs
test/support/conn_case.ex
test/support/test_helpers.ex
web/controllers/auth.ex
web/controllers/page_controller.ex
web/controllers/session_controller.ex
web/controllers/user_controller.ex
web/router.ex
web/templates/layout/app.html.eex
web/templates/session/new.html.eex
web/templates/user/form.html.eex
web/views/session_view.ex
web/web.ex

Login flow

---

priv/repo/migrations/20170510114320_add_terms_and_conditions.exs
test/controllers/user_controller_test.exs
test/models/user_test.exs
test/support/test_helpers.ex
web/models/user.ex
web/templates/user/new.html.eex

Terms conditions

---

Procfile
config/prod.exs
web/channels/user_socket.ex
web/templates/session/new.html.eex
web/templates/user/new.html.eex

https://karmaradio.herokuapp.com/
#29

deploy to Heroku 

---

lib/email.ex
test/controllers/user_controller_test.exs
web/controllers/user_controller.ex
web/controllers/verification_controller.ex
web/templates/email/verify.html.eex
web/templates/email/verify.text.eex
web/templates/layout/email.html.eex
web/templates/layout/email.text.eex
web/views/email_view.ex

Email View + Verified Login

---

lib/email.ex
test/controllers/session_controller_test.exs
test/controllers/verification_controller_test.exs
web/controllers/helpers.ex
web/controllers/session_controller.ex
web/controllers/user_controller.ex
web/controllers/verification_controller.ex
web/router.ex
web/templates/verification/verify_again.html.eex
web/views/verification_view.ex

Resend verification

---

test/controllers/dashboard_controller_test.exs
test/views/view_helpers_test.exs
web/controllers/dashboard_controller.ex
web/static/css/app.css
web/templates/component/project_tile.html.eex
web/templates/dashboard/index.html.eex
web/templates/layout/app.html.eex
web/views/view_helpers.ex
web/web.ex

Dashboard style

---

test/controllers/project_controller_test.exs
web/controllers/project_controller.ex
web/router.ex
web/static/css/app.css
web/templates/component/button.html.eex
web/templates/component/offer_tile.html.eex
web/templates/component/project_tile.html.eex
web/templates/layout/no_container.html.eex
web/templates/project/offers.html.eex

Project Offer View

---

test/controllers/offer_controller_test.exs
web/controllers/offer_controller.ex
web/models/offer.ex
web/templates/component/offer_tile.html.eex
web/templates/offer/index.html.eex

Offers index

---

test/controllers/offer_controller_test.exs
test/controllers/project_controller_test.exs
web/controllers/offer_controller.ex
web/controllers/project_controller.ex
web/templates/offer/show.html.eex

Offers show

---

test/controllers/offer_controller_test.exs

Adds basic test for new offer form
#61

new offer form

---

test/controllers/offer_controller_test.exs
web/controllers/offer_controller.ex
web/templates/offer/show.html.eex

pm can edit pending offers
can't edit accepted/rejected
get edit and post update 
#65

WIP Edit/update offer

---

test/controllers/offer_controller_test.exs
test/models/offer_test.exs

Finish tests for offer controller

---

web/controllers/password_controller.ex
web/templates/password/edit.html.eex

forgot password bug

---

lib/email.ex
test/controllers/offer_controller_test.exs
web/controllers/offer_controller.ex
web/templates/email/updated_offer.html.eex
web/templates/email/updated_offer.text.eex

Email update offer

---

web/static/css/app.css
web/templates/component/input.html.eex
web/templates/user/new.html.eex

closes #81
fixes bugs in #2 (assign Jono & remove bug label)

create account fields

---

test/controllers/offer_controller_test.exs
web/controllers/helpers.ex
web/controllers/offer_controller.ex
web/models/offer.ex

This is to merge into the open PR #86 
Add form_validation changeset
Run form validation before doing calculations
Move calculation functions into a helper function
#88

Refactor add offers

---

web/templates/component/date.html.eex
web/templates/component/input.html.eex
web/templates/project/form.html.eex

remove autocomplete
fix field labels
date select default to today
...
#4

Project form bug

---

test/controllers/project_controller_test.exs
web/controllers/project_controller.ex
web/models/project.ex
web/static/assets/images/plus.svg
web/templates/component/offer_tile.html.eex
web/templates/component/plus_button.html.eex
web/templates/dashboard/index.html.eex
web/templates/offer/edit.html.eex
web/templates/offer/index.html.eex
web/templates/offer/new.html.eex
web/templates/offer/show.html.eex
web/templates/project/edit.html.eex
web/templates/project/form.html.eex
web/templates/project/new.html.eex
web/templates/project/show.html.eex
web/templates/user/edit.html.eex
web/templates/user/show.html.eex

Navigation fix

---

test/controllers/password_controller_test.exs
web/controllers/password_controller.ex
web/templates/component/input.html.eex
web/templates/password/edit.html.eex
web/templates/password/new.html.eex

Forgot password 404 bug 
password confirmation type=password
#15

fixes forgot password flow

---

test/views/dashboard_view_test.exs
test/views/page_view_test.exs
web/controllers/dashboard_controller.ex
web/controllers/offer_controller.ex
web/templates/dashboard/index.html.eex
web/templates/offer/index.html.eex
web/views/dashboard_view.ex
web/views/view_helpers.ex

Offer stats

---

web/templates/session/new.html.eex

password hidden field, autofill on in login view
#101 -

login bugs

---

web/templates/offer/edit.html.eex

Minor Nav Fix

---

web/controllers/dashboard_controller.ex

Project Root Not Logged In

---

test/controllers/password_controller_test.exs
web/controllers/session_controller.ex
web/templates/offer/show.html.eex

Calculated Offer Fields

---

web/templates/component/plus_button.html.eex
web/templates/dashboard/index.html.eex
web/templates/project/edit.html.eex

Minor Nav Fix...again

---

web/templates/project/form.html.eex

Field Fix - Project

---

test/models/offer_test.exs
web/models/offer.ex
web/templates/offer/form.html.eex

Conditional fields make offer

---

priv/repo/migrations/20170523092230_add_conditional_required_fields_offers_table.exs
test/controllers/offer_controller_test.exs
web/controllers/offer_controller.ex
web/models/offer.ex
web/templates/offer/edit.html.eex
web/templates/offer/form.html.eex
web/templates/offer/new.html.eex
web/templates/project/edit.html.eex
web/templates/project/form.html.eex
web/templates/user/edit.html.eex
web/templates/user/form.html.eex

- small refactor on offer actions (render function too big)
- add migration to add the conditional required? fields to db (Don't forget to migrate)
- add check to update action to see if offer has actually been updated
Doesn't re run calculations after an update - will do that in another pr
https://github.com/karmaradio/karma/issues/12#issuecomment-303176659

Make offer update bug

---

web/templates/user/new.html.eex

Hide Password

---

priv/repo/migrations/20170524131436_create_startpack.exs
test/controllers/startpack_controller_test.exs
test/models/startpack_test.exs
web/controllers/startpack_controller.ex
web/models/startpack.ex
web/router.ex
web/templates/startpack/edit.html.eex
web/templates/startpack/form.html.eex
web/templates/startpack/index.html.eex
web/templates/startpack/new.html.eex
web/templates/startpack/show.html.eex
web/views/startpack_view.ex

Initial generator for startpack

---

README.md
schema.md

#37 - add getting started to readme

---

config/config.exs
lib/S3.ex
test/controllers/s3_test.exs
test/controllers/startpack_controller_test.exs
web/controllers/startpack_controller.ex
web/templates/startpack/form.html.eex

Upload file async

---

web/templates/component/checkbox.html.eex
web/templates/component/date.html.eex
web/templates/startpack/form.html.eex

#170 
Puts the startpack/id/edit form into components & tachyons

add startpack form to components

---

web/templates/offer/show.html.eex

Offer Show

---

test/models/startpack_test.exs
web/models/startpack.ex

adds validation for startpack when vehicle allowance > 0
#194

add vehicle allowance validation.

---

lib/email.ex
test/controllers/offer_controller_test.exs
web/controllers/offer_controller.ex
web/templates/email/offer_accepted_contractor.html.eex
web/templates/email/offer_accepted_contractor.text.eex
web/templates/email/offer_response_pm.html.eex
web/templates/email/offer_response_pm.text.eex

Offer email

---

web/templates/layout/app.html.eex
web/templates/offer/edit.html.eex
web/templates/offer/new.html.eex
web/templates/project/edit.html.eex
web/templates/project/new.html.eex
web/templates/startpack/edit.html.eex
web/templates/startpack/index.html.eex
web/templates/user/edit.html.eex

- Added max width (mw9) to main containers
Fixes issue #155

Containers width

---

web/templates/dashboard/index.html.eex

Took out grey backgrounds from dashboard view 

---

lib/email.ex
test/controllers/offer_controller_test.exs
test/controllers/user_controller_test.exs
web/controllers/offer_controller.ex
web/templates/email/new_offer_registered.html.eex
web/templates/email/new_offer_registered.text.eex
web/templates/email/new_offer_unregistered.html.eex
web/templates/email/new_offer_unregistered.text.eex
web/templates/email/password_reset.html.eex
web/templates/email/password_reset.text.eex
web/templates/email/updated_offer.html.eex
web/templates/email/updated_offer.text.eex
web/templates/email/verify.html.eex
web/templates/email/verify.text.eex
web/templates/layout/email.html.eex
web/templates/layout/email.text.eex

#43 
Awaiting templates for:
- contractor: accepted offer
- PM: someone has responded to an offer

Email templates

---

web/controllers/offer_controller.ex
web/templates/offer/form.html.eex
web/templates/project/form.html.eex

Sprint 1 fixes

---

test/models/startpack_test.exs
web/models/startpack.ex
web/templates/component/radio.html.eex
web/templates/startpack/form.html.eex
web/views/startpack_view.ex

Validate contract type

---

web/models/startpack.ex
web/templates/startpack/form.html.eex

 fix comments

---

web/controllers/user_controller.ex
web/templates/component/input.html.eex
web/templates/user/new.html.eex
web/views/error_helpers.ex

Closing last pull request and made this new one with a new branch name.
tweaks to login pages including error views.

Login tweaks

---

web/templates/component/offer_tile.html.eex
web/templates/component/project_tile.html.eex
web/templates/offer/show.html.eex
web/templates/startpack/form.html.eex

Minor FIxes

---

web/static/css/app.css
web/templates/component/checkbox.html.eex
web/templates/layout/app.html.eex
web/templates/password/new.html.eex
web/templates/session/new.html.eex
web/templates/user/new.html.eex

Added focus field colour on input fields to indicate to the user where they are.
Fixes issue #156 (see screen grabs in issue)
(Apologies, this pull request contains the last pull request code as well #222)

Focus input

---

test/models/startpack_test.exs
web/models/startpack.ex
web/static/js/app.js
web/templates/component/file_upload.html.eex
web/templates/component/radio.html.eex
web/templates/startpack/edit.html.eex
web/templates/startpack/form.html.eex
web/templates/startpack/index.html.eex

add startpack comments from jono
add student loan logic
https://github.com/karmaradio/karma/issues/6#issuecomment-304912148

Startpack comments

---

test/models/startpack_test.exs
web/models/startpack.ex
web/static/css/app.css
web/static/js/app.js
web/templates/component/file_upload.html.eex
web/templates/component/radio.html.eex
web/templates/startpack/edit.html.eex
web/templates/startpack/form.html.eex
web/templates/startpack/index.html.eex

Adds conditional checkboxes to startpack form
#6

Conditional checkbox

---

web/templates/component/form_divider.html.eex
web/templates/offer/form.html.eex
web/templates/project/form.html.eex

adding dividers to forms to make them more accessible for the user and start applying logic for future division
#163

Add dividers create project page  #163 

---

web/templates/dashboard/index.html.eex
web/templates/offer/index.html.eex

added border radius on banners and made banners all same width #236

---

web/templates/component/offer_tile.html.eex

changed the yellow bg-gold with the apps accent colour yellow 

---

web/templates/component/form_divider.html.eex
web/templates/offer/form.html.eex
web/templates/startpack/form.html.eex

added dividers on startpack form and changed a bit the header style 

---

web/templates/component/dropdown.html.eex

@jonscottfilm needs to check on his machine as it seems like that is where this bug is showing so lets merge it so he can check! :)

added border radius to dropdown text area fixes #236

---

README.md
web/templates/password/edit.html.eex
web/templates/password/new.html.eex
web/templates/session/new.html.eex
web/templates/user/new.html.eex

Also added styles to reset password page 
fixes #150

Fixed all login flow to be responsive and layout bug fixed

---

schema.md
test/models/startpack_test.exs
web/models/startpack.ex

fixes student loan bug causing offer crash
can close:
#244

Student loan bug

---

README.md
web/static/css/app.css
web/templates/component/input.html.eex
web/templates/component/number_input.html.eex
web/templates/component/textarea.html.eex

Placeholder to disappear when user click input for better usability 
fixes #157

Placeholder to disappear 

---

test/controllers/offer_controller_test.exs
web/controllers/offer_controller.ex
web/controllers/project_controller.ex
web/controllers/user_controller.ex
web/router.ex
web/templates/offer/show.html.eex
web/templates/startpack/form.html.eex

Receive offer bug and contractor permissions

---

web/static/css/app.css
web/templates/component/file_upload.html.eex

Startpack validation

---

web/controllers/offer_controller.ex
web/models/offer.ex
web/static/js/departments_with_jobs.js

Contract Type

---

web/templates/startpack/form.html.eex

Middle name Fix

---

web/templates/password/edit.html.eex

fixed layout on reset password page 

---

web/templates/offer/show.html.eex

Recipient Email

---

lib/email.ex
web/controllers/offer_controller.ex

Offer response

---

test/controllers/document_controller_test.exs
test/controllers/startpack_controller_test.exs
web/controllers/document_controller.ex
web/controllers/startpack_controller.ex
web/models/document.ex
web/models/startpack.ex
web/templates/component/file_upload.html.eex
web/views/view_helpers.ex

adds restriction to project documents (pdf only)
adds restriction to startpack documents (pdf, jpg, png)
#9
#287

Restrict file uploads

---

config/prod.exs

Undo HTTPS

---

lib/merger.ex
test/controllers/helpers_test.exs
test/lib/merger_test.exs
web/controllers/helpers.ex

Get all data function for merge

---

web/static/css/app.css
web/templates/component/offer_tile.html.eex
web/templates/component/project_tile.html.eex

took out uncommented code and fixed css top--header class

fix layout dashboard view

---

web/static/css/app.css
web/templates/component/offer_tile.html.eex
web/templates/component/project_tile.html.eex
web/templates/layout/app.html.eex

changed footer according to @jonscottfilm feedback.
Fixes #243

Fix footer

---

web/templates/component/offer_tile.html.eex
web/templates/offer/index.html.eex

changed project view page layout to look similar to the dashboard view
#297

New layout - project view

---

web/templates/component/offer_tile.html.eex
web/templates/component/plus_button.html.eex
web/templates/dashboard/index.html.eex
web/templates/offer/index.html.eex

dependant on the last PR to be merged because containing code from the last commit

Small fixes 

---

web/static/assets/images/ic_check.svg
web/templates/component/offer_tile.html.eex
web/templates/component/project_tile.html.eex
web/templates/offer/index.html.eex

- Changes letters to icons and bg colours of ovals and fonts:
- pending: "..." and grey for both font and oval bg
- accepted: "✔︎" and darker green for both font and oval bg
- rejected: "x" and red for both font and bg
- changes colours also on project tiles in dashboard and projects details page

changed traffic light system on offer tiles #317

---

web/templates/offer/index.html.eex

took out underline from tiles and made date smaller

---

web/templates/offer/new.html.eex
web/templates/project/new.html.eex
web/templates/startpack/form.html.eex
web/templates/startpack/index.html.eex

changed headers on forms views to look similar to dashboard header and project details header

Headers in forms

---

test/controllers/offer_controller_test.exs
web/controllers/offer_controller.ex
web/router.ex
web/templates/offer/show.html.eex

Refactor Offer Response

---

web/templates/dashboard/index.html.eex
web/templates/offer/index.html.eex

Plus button

---

web/templates/document/form.html.eex
web/templates/layout/app.html.eex
web/templates/offer/form.html.eex
web/templates/password/edit.html.eex
web/templates/password/new.html.eex
web/templates/project/form.html.eex
web/templates/user/form.html.eex
web/templates/user/new.html.eex

Error message fix

---

package.json

reinstall dependencies 

---

schema.md
test/controllers/helpers_test.exs
test/models/startpack_test.exs
web/controllers/helpers.ex
web/controllers/offer_controller.ex
web/models/offer.ex
web/models/startpack.ex
web/templates/project/show.html.eex

Merging into merge function
- unify contract types
- dynamically choose contract to be merged with
#295

Unify contract types

---

web/controllers/offer_controller.ex
web/models/document.ex

Some small changes to get a manual test working
#295

Merge small fixes

---

lib/merger.ex

generate file name depending on original file name

---

web/controllers/offer_controller.ex
web/templates/offer/show.html.eex

Add merged url to offer

---

test/controllers/offer_controller_test.exs
web/controllers/offer_controller.ex

- Add tests
- Add 1 permissions plug
- Fix some old tests that were passing but shouldn't have been
- Remove error handling of final documents table insert

Add tests to merger

---

test/lib/merger_test.exs

#295 
Adds more tests to merge function

add tests for merger function

---

web/models/startpack.ex

Ensure startpack validates fields depending on startpack 
#201 - can be put in please test

add contract type startpack validation

---

web/templates/layout/app.html.eex

#119 - update mailto link

---

web/templates/startpack/form.html.eex
web/templates/startpack/index.html.eex

adds more startpack styling

---

web/static/css/app.css
web/templates/component/dropdown.html.eex
web/templates/component/input.html.eex
web/templates/component/number_input.html.eex
web/templates/component/textarea.html.eex

Input Border

---

web/static/css/app.css

Navbar Adjustment

---

lib/format.ex
lib/merger.ex
test/lib/merger_test.exs
test/support/test_helpers.ex
web/controllers/offer_controller.ex

Data format

---

priv/repo/migrations/20170619151847_split_documents_tables.exs
test/controllers/offer_controller_test.exs
test/models/altered_document_test.exs
web/controllers/offer_controller.ex
web/models/altered_document.ex
web/models/document.ex
web/models/offer.ex
web/templates/offer/show.html.eex

@jackcarlisle can you try to pull down, run migration and run locally? I had an issue with migrating so had to drop my tables so I'm not sure how it will play on your machine/heroku.
#392

Split documents tables

---

priv/repo/migrations/20170619142015_create_signee.exs
priv/repo/migrations/20170619150608_add_email_to_signee.exs
test/controllers/signee_controller_test.exs
test/models/signee_test.exs
test/support/test_helpers.ex
web/controllers/helpers.ex
web/controllers/project_controller.ex
web/controllers/signee_controller.ex
web/models/project.ex
web/models/signee.ex
web/router.ex
web/static/css/app.css
web/templates/project/show.html.eex
web/templates/user/new.html.eex
web/views/signee_view.ex

Add signees to project

---

config/config.exs
config/prod.exs
lib/sign.ex
mix.exs
test/lib/sign_test.exs
test/models/altered_document_test.exs

Docusign auth

---

lib/merger.ex
test/controllers/offer_controller_test.exs
test/lib/merger_test.exs
web/controllers/offer_controller.ex
web/templates/offer/show.html.eex
web/templates/project/show.html.eex
web/views/document_signee_view.ex

Multiple Document Merge

---

test/controllers/offer_controller_test.exs
test/models/altered_document_test.exs
web/controllers/helpers.ex
web/controllers/offer_controller.ex
web/models/document.ex
web/models/offer.ex
web/templates/project/show.html.eex

add logic for which forms are retrieved for merging
see issue for tasklist
#409 -

add queries for conditional forms

---

lib/S3.ex
lib/sign.ex
test/controllers/altered_document_controller_test.exs
test/lib/sign_test.exs
test/support/test_helpers.ex
web/controllers/altered_documents_controller.ex
web/models/altered_document.ex
web/router.ex
web/templates/offer/show.html.eex

See issue for tasklist: https://github.com/karmaradio/karma/issues/391
#391

Prepare docusign envelope

---

test/controllers/offer_controller_test.exs
web/controllers/helpers.ex
web/controllers/offer_controller.ex
web/templates/offer/show.html.eex

Offer View Document Format

---

web/templates/project/show.html.eex

fix formatting bug for add signee to project

---

lib/sign.ex
test/lib/sign_test.exs

add email body and subject to document sign request

---

priv/repo/migrations/20170623141207_add-signee-project-unique-index.exs
test/controllers/signee_controller_test.exs
web/models/signee.ex
web/templates/offer/show.html.eex
web/templates/project/show.html.eex

add confirm delete signee
prevent 2 of same signee uploaded to each project
#393

Add signee fixes

---

priv/repo/migrations/20170623141207_add-signee-project-unique-index.exs
test/controllers/signee_controller_test.exs
web/models/signee.ex
web/templates/offer/show.html.eex
web/templates/project/show.html.eex

View offer bug

---

lib/sign.ex

fix docusign timout bug

---

web/templates/project/show.html.eex

fixes no signee message to PM
#387 -

update message to pm when no signees are added to a project

---

web/templates/project/show.html.eex

https://github.com/karmaradio/karma/issues/401#issuecomment-311038517

fix styling bug when no signees added to project

---

web/templates/project/show.html.eex
web/templates/signee/new.html.eex

 fix the wording for adding signees to a document.

---

test/controllers/offer_controller_test.exs
web/controllers/offer_controller.ex
web/templates/component/file_upload.html.eex
web/templates/dashboard/index.html.eex
web/templates/offer/show.html.eex

Supporting Documents

---

test/controllers/offer_controller_test.exs
web/controllers/helpers.ex
web/controllers/offer_controller.ex
web/models/document.ex

Loan out contract

---

web/controllers/offer_controller.ex

NDA + Other Documents

---

web/templates/offer/show.html.eex

Offer view order

---

web/controllers/offer_controller.ex
web/templates/offer/show.html.eex

Offer recipient

---

priv/repo/migrations/20170703131134_add_insurance_and_license_to_startpack.exs
test/controllers/startpack_controller_test.exs
test/models/startpack_test.exs
web/models/startpack.ex
web/templates/startpack/form.html.eex

Adds license and business insurance upload fields to starpack

---

web/templates/offer/show.html.eex

Box Equipment Vehicle Fields 

---

web/models/offer.ex
web/templates/startpack/form.html.eex

Offer target email format

---

web/templates/component/radio.html.eex
web/templates/startpack/form.html.eex

fixes checkbox hiding half of startpack (#450 )
fixes copy error (#444)

Checkbox bug

---

lib/sign.ex
priv/repo/migrations/20170705080045_add_approver_type_to_signees.exs
schema.md
test/controllers/signee_controller_test.exs
test/lib/sign_test.exs
test/models/signee_test.exs
test/support/test_helpers.ex
web/controllers/helpers.ex
web/controllers/signee_controller.ex
web/models/signee.ex
web/templates/project/show.html.eex
web/templates/signee/new.html.eex

Add recipients to documents
See [comment](https://github.com/karmaradio/karma/issues/448#issuecomment-313028887) for tasklist
#448

add approver_type to signees

---

web/controllers/startpack_controller.ex

Licence Typo

---

lib/sign.ex
test/lib/sign_test.exs
test/support/test_helpers.ex
web/templates/offer/show.html.eex

Ensure recipient receives email last, not first
#476

Recipient receives last

---

web/templates/offer/show.html.eex

Ready
Add warning of long loading
#462 -

add warning of 30 second signing delay

---

lib/sign.ex
test/controllers/altered_document_controller_test.exs
test/lib/sign_test.exs
web/controllers/altered_documents_controller.ex

update blurb and subject
update filename
#434

Docusign email content

---

priv/repo/migrations/20170706145813_add_vehicle_required_to_startpack.exs
test/controllers/startpack_controller_test.exs
test/support/test_helpers.ex
web/controllers/startpack_controller.ex
web/models/startpack.ex
web/templates/offer/form.html.eex
web/templates/startpack/form.html.eex

Vehicle checkbox

---

web/templates/component/input.html.eex
web/templates/dashboard/index.html.eex
web/templates/offer/form.html.eex
web/templates/offer/new.html.eex
web/templates/project/form.html.eex
web/templates/project/new.html.eex

Placeholder Cleanup

---

web/static/js/app.js
web/static/js/departments_with_jobs.js

fixes job title dropdown

---

web/templates/dashboard/index.html.eex
web/templates/offer/show.html.eex

Breadcrumb Fix

---

web/templates/offer/form.html.eex

fixes placeholders

---

web/templates/session/new.html.eex

Password Placeholder

---

web/templates/project/show.html.eex

Project Documents Dropdown

---

web/controllers/offer_controller.ex
web/models/offer.ex
web/models/user.ex

Offer email format

---

lib/format.ex
priv/repo/migrations/20170707130038_change_integers_to_floats.exs
test/controllers/helpers_test.exs
web/controllers/helpers.ex
web/controllers/offer_controller.ex
web/models/offer.ex

Calculation Fix

---

web/templates/info/terms.html.eex

Terms and conditions

---

test/controllers/info_controller_test.exs
web/templates/component/offer_tile.html.eex
web/templates/component/project_tile.html.eex
web/templates/info/terms.html.eex
web/templates/offer/index.html.eex
web/templates/offer/show.html.eex
web/templates/project/form.html.eex
web/templates/project/show.html.eex
web/templates/session/new.html.eex
web/templates/signee/new.html.eex
web/templates/user/new.html.eex

General fixes

---

test/models/startpack_test.exs
web/models/startpack.ex
web/templates/offer/show.html.eex

Vehicle changeset fix

---

test/controllers/startpack_controller_test.exs
web/controllers/startpack_controller.ex
web/static/css/app.css
web/templates/startpack/form.html.eex

Vehicle Logic

---

web/templates/signee/new.html.eex

Breadcrumbs

---

web/static/css/app.css
web/templates/dashboard/index.html.eex

More Minor Fixes

---

test/controllers/signee_controller_test.exs
web/templates/signee/new.html.eex

Signees -> Approvers

---

web/templates/info/terms.html.eex

Remove indent

---

web/static/css/app.css
web/templates/layout/app.html.eex

Burger Menu

---

web/controllers/helpers.ex

Conditional Contract

---

lib/format.ex
test/controllers/startpack_controller_test.exs
test/models/startpack_test.exs
web/controllers/offer_controller.ex
web/controllers/startpack_controller.ex
web/models/startpack.ex
web/templates/offer/show.html.eex

Ready 
Moves 'bring own vehicle' logic into the main mother changeset
Upcases currency
#528

Bring own vehicle bug

---

lib/email.ex

Email subject fix

---

test/controllers/offer_controller_test.exs
web/templates/email/offer_response_pm.html.eex
web/templates/offer/form.html.eex

Fix fee per day float

---

web/models/startpack.ex

ready
Loan out company should be unchecked by default
#524 -

Make loan out company false by default

---

web/templates/layout/app.html.eex

add website url to footer

---

test/controllers/offer_controller_test.exs
web/controllers/helpers.ex

ready
vehicle allowance form was merging regardless of allowance given in offer
#524 -

 only merge vehicle allowance form if vehicle allowance above 0

---

web/static/js/app.js
web/templates/layout/app.html.eex
web/templates/offer/form.html.eex

converts all number inputs to regular numbers (not scientific notation)
#524

convert scientific notation into regular

---

web/templates/layout/app.html.eex

increases fontweight of engine in nav
displays logo in 'terms of use view'
#524

Engine font weight

---

priv/repo/migrations/20170716102539_vehicle_allowance_float.exs
web/models/offer.ex
web/static/js/app.js
web/templates/component/number_input.html.eex

Float inputs

---

priv/repo/migrations/20170716114006_rental_allowance_float.exs
web/models/startpack.ex

ready
allow rental allowance to be floats
#542

Allow rental allowance to be floats

---

web/templates/component/form_divider.html.eex
web/templates/startpack/form.html.eex

ready
Adds space and dividers to startpack form
#524

Startpack form ux

---

config/config.exs
config/prod.exs

ready
Use correct config for docusign live account
#524

Docusign live account

---

test/controllers/helpers_test.exs
web/controllers/helpers.ex

ready
Only certain department & job title combinations should 'convert' to SCHEDULE-D
#542

contract type PAYE to SCH-D if provision of equipment

---

web/templates/email/offer_response_pm.html.eex

Ready
Make bold 'accepted'/'rejected'
#542

#542 - bold the offer status in email

---

web/templates/email/new_offer_registered.html.eex
web/templates/email/new_offer_unregistered.html.eex
web/templates/email/offer_accepted_contractor.html.eex
web/templates/email/offer_response_pm.html.eex
web/templates/email/password_reset.html.eex
web/templates/email/updated_offer.html.eex
web/templates/email/verify.html.eex

ready
header logo should not be a link
attempt to remove word image from all images
#524

Email links

---

lib/sign.ex
test/lib/sign_test.exs

Remove 'daily' or 'weekly' from docusign filename

Docusign file name remove daily / weekly

---

lib/email.ex
test/controllers/offer_controller_test.exs
test/controllers/password_controller_test.exs
test/controllers/user_controller_test.exs
web/templates/component/email_footer.html.eex
web/templates/email/new_offer_registered.html.eex
web/templates/email/new_offer_unregistered.html.eex
web/templates/email/offer_accepted_contractor.html.eex
web/templates/email/offer_response_pm.html.eex
web/templates/email/password_reset.html.eex
web/templates/email/updated_offer.html.eex
web/templates/email/verify.html.eex

See issue for task list
#556 -

split email footer into a component and fix email content

---

web/templates/offer/show.html.eex

ready
Fix bug if no documents uploaded before offer accepted
#560 -

fix no documents to merge causing crash

---

web/templates/component/email_footer.html.eex

Ready when @jonscottfilm  says so.
Center the email footer
#556

Center the logo in email footer

---

priv/repo/migrations/20170827080639_add_offer_end_date.exs
schema.md
test/models/offer_test.exs
test/support/test_helpers.ex
web/models/offer.ex
web/templates/component/date.html.eex
web/templates/offer/form.html.eex
web/templates/offer/show.html.eex
web/views/view_helpers.ex

add offer end date (not validated - will open another PR)
#567

add end_date to offers

---

web/templates/component/date.html.eex
web/templates/offer/form.html.eex
web/templates/startpack/form.html.eex

ready
task list: https://github.com/karmaradio/karma/issues/600#issuecomment-325376625
#600

Fix date reset bug

---

lib/format.ex
web/templates/startpack/form.html.eex

ready
format offer_end_date and passport expiry date for merge
remove 10 year upper limit for passport expiry
remove 16 year lower limit for dob 
#600

small formatting and date related fixes

---

lib/merger.ex
priv/repo/migrations/20170828170131_add_loan_out_company_email.exs
schema.md
test/models/startpack_test.exs
web/models/startpack.ex
web/templates/startpack/form.html.eex

adds loan out company email required field
#416

Adds loan out company email

---

web/templates/offer/show.html.eex

Ready
amend warning messages
#581

amend warning messages to PM

---

lib/format.ex
lib/merger.ex

Add offer_updated_at to merge data

add offer_updated_at to offer merge data

---

lib/email.ex
web/controllers/password_controller.ex

Swaps http out for https in urls being sent via emails.
#612

remove http links in emails

---

test/controllers/offer_controller_test.exs
web/controllers/offer_controller.ex
web/templates/offer/edit.html.eex
web/templates/offer/form.html.eex
web/templates/offer/new.html.eex

Overwrite Fullname

---

web/templates/offer/show.html.eex

Accept Reject Buttons

---

test/controllers/password_controller_test.exs
web/controllers/offer_controller.ex
web/controllers/password_controller.ex
web/templates/offer/show.html.eex

Contractor Contact Project

---

web/templates/offer/show.html.eex
web/templates/startpack/form.html.eex
web/templates/startpack/index.html.eex

Offer button

---

web/models/startpack.ex

Equipment Rental Changeset

---

priv/repo/migrations/20170928100129_add_operating_contact_to_project.exs
web/static/css/app.css
web/templates/component/input.html.eex
web/templates/component/number_input.html.eex
web/templates/offer/show.html.eex
web/templates/startpack/index.html.eex

Error messages

---

priv/repo/migrations/20170928100129_add_operating_contact_to_project.exs
test/support/test_helpers.ex
web/models/project.ex
web/templates/component/data.html.eex
web/templates/offer/show.html.eex
web/templates/project/form.html.eex
web/templates/project/show.html.eex

Operating base contact

---

web/templates/layout/app.html.eex
web/templates/session/new.html.eex

Forgotten password link

---

web/templates/verification/verify_again.html.eex

Verification View

---

web/templates/offer/show.html.eex
web/templates/startpack/form.html.eex

Passport fullname

---

web/templates/info/privacy.html.eex
web/templates/startpack/form.html.eex

Startpack gender

---

test/controllers/offer_controller_test.exs
web/controllers/helpers.ex
web/templates/project/show.html.eex

Box/Equipment Rental -> Inventory

---

test/controllers/project_controller_test.exs
test/controllers/startpack_controller_test.exs
web/controllers/project_controller.ex
web/controllers/startpack_controller.ex
web/models/offer.ex
web/models/project.ex
web/models/startpack.ex
web/static/css/app.css
web/templates/layout/app.html.eex
web/templates/offer/form.html.eex
web/templates/offer/show.html.eex
web/templates/password/edit.html.eex
web/templates/project/form.html.eex
web/templates/startpack/form.html.eex
web/templates/startpack/index.html.eex
web/templates/verification/verify_again.html.eex

Character limit 300

---

lib/job.ex
web/static/js/departments_with_jobs.js

Location Manager PAYE

---

web/static/css/app.css
web/templates/component/offer_tile.html.eex
web/views/view_helpers.ex

Offer tile date

---

lib/merger.ex
priv/repo/migrations/20171006100448_add_sent_to_offers.exs
web/controllers/custom_field_controller.ex
web/controllers/offer_controller.ex
web/models/offer.ex
web/router.ex
web/static/css/app.css
web/templates/component/submit_button.html.eex
web/templates/custom_field/add.html.eex
web/templates/offer/edit.html.eex
web/templates/offer/form.html.eex
web/templates/offer/show.html.eex
web/templates/project/show.html.eex

Staging fix

---

lib/format.ex
lib/merger.ex
test/controllers/custom_field_controller_test.exs
test/controllers/offer_controller_test.exs
test/controllers/project_controller_test.exs
test/lib/merger_test.exs
test/models/custom_field_test.exs
test/support/test_helpers.ex
web/controllers/custom_field_controller.ex
web/controllers/dashboard_controller.ex
web/controllers/offer_controller.ex
web/models/offer.ex
web/static/css/app.css
web/static/js/app.js
web/templates/component/input.html.eex
web/templates/component/offer_tile.html.eex
web/templates/component/submit_button.html.eex
web/templates/custom_field/add.html.eex
web/templates/dashboard/index.html.eex
web/templates/offer/form.html.eex
web/templates/offer/index.html.eex
web/templates/offer/new.html.eex
web/templates/offer/show.html.eex
web/templates/project/show.html.eex
web/views/view_helpers.ex

Test coverage

---

web/controllers/dashboard_controller.ex
web/controllers/offer_controller.ex
web/models/offer.ex
web/static/css/app.css
web/templates/component/offer_tile.html.eex
web/templates/offer/form.html.eex

Small fixes

---

web/controllers/custom_field_controller.ex
web/controllers/helpers.ex

Offer update

---

web/templates/dashboard/index.html.eex
web/templates/offer/show.html.eex

Offers viewed

---

web/templates/offer/show.html.eex

Offer view Sixth Seventh Holiday Pay

---

web/controllers/helpers.ex
web/controllers/offer_controller.ex
web/templates/offer/edit.html.eex
web/templates/offer/form.html.eex

Offer order

---

test/controllers/admin_dashboard_controller_test.exs
web/controllers/auth.ex
web/templates/offer/form.html.eex

300 Char limit

---

web/controllers/auth.ex
web/controllers/offer_controller.ex
web/controllers/project_controller.ex
web/templates/offer/show.html.eex

Document Merge Order

---

web/templates/layout/app.html.eex

Website Url -> New tab

---

lib/S3.ex
test/controllers/s3_test.exs
web/controllers/document_controller.ex
web/controllers/startpack_controller.ex

Upload filename

---

lib/S3.ex
test/controllers/offer_controller_test.exs
test/controllers/s3_test.exs
web/controllers/offer_controller.ex
web/templates/offer/edit.html.eex
web/templates/offer/show.html.eex

Offer create and update flow - no custom fields

---

lib/merger.ex
test/lib/merger_test.exs

Form upload fix

---

departments_with_jobs.json
lib/S3.ex
lib/job.ex
test/controllers/helpers_test.exs
test/controllers/offer_controller_test.exs
test/controllers/s3_test.exs
test/controllers/signee_controller_test.exs
web/controllers/document_controller.ex
web/controllers/helpers.ex
web/controllers/offer_controller.ex
web/controllers/project_controller.ex
web/controllers/startpack_controller.ex
web/models/project.ex
web/static/js/departments_with_jobs.js
web/templates/project/show.html.eex
web/templates/signee/new.html.eex
web/templates/startpack/form.html.eex

List fixes

---

web/controllers/dashboard_controller.ex
web/controllers/offer_controller.ex
web/templates/component/offer_tile.html.eex

Docusign offer status

---

web/templates/startpack/form.html.eex

Startpack loan out section

---

fieldnames.md
lib/merger.ex

Startpack address block merged fields

---

test/controllers/startpack_controller_test.exs
web/controllers/startpack_controller.ex

Student loan startpack

---

web/templates/component/button.html.eex
web/templates/project/show.html.eex

Approver Button

---

lib/format.ex
lib/merger.ex
test/lib/merger_test.exs
test/support/test_helpers.ex

Agent & Loan out

---

web/templates/verification/verify_again.html.eex

Verification Button

---

lib/format.ex
lib/merger.ex

Merge field fix

---

web/templates/offer/show.html.eex

Company name in offer

---

test/views/view_helpers_test.exs
web/controllers/offer_controller.ex
web/templates/offer/show.html.eex
web/views/view_helpers.ex

Contract - Offer view

---

fieldnames.md
lib/merger.ex
priv/repo/migrations/20171020092055_add_job_title_suffix_to_offer.exs
web/models/offer.ex
web/templates/offer/form.html.eex
web/templates/offer/show.html.eex

Adds Job title suffix

---

web/templates/project/form.html.eex
web/templates/startpack/form.html.eex

300 characters

---

web/templates/offer/form.html.eex
web/templates/offer/show.html.eex

Download Instruction

---

lib/sign.ex
test/lib/sign_test.exs
web/templates/offer/form.html.eex

Loan out > Approval Chain
